### ISSUE TITLE
6 errors, 3 warnings

### ISSUE THREAD

**Issue by bright79** [wxapp-book/calendar#2]
直接加载代码，修复一个语法错误后，出现下面问题。敬请编者核实下：
Errors 1:  VM1451:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property '\_' of undefined 
 TypeError: Cannot read property '_' of undefined
    at http://127.0.0.1:50038/appservice/lib/underscore.js:19:34
    at http://127.0.0.1:50038/appservice/lib/underscore.js:1577:4
    at require (http://127.0.0.1:50038/appservice/__dev__/WAService.js:18:27248)
    at http://127.0.0.1:50038/appservice/__dev__/WAService.js:18:26997
    at http://127.0.0.1:50038/appservice/common/js/wx.js:4:10
    at require (http://127.0.0.1:50038/appservice/__dev__/WAService.js:18:27248)
    at http://127.0.0.1:50038/appservice/__dev__/WAService.js:18:26997
    at http://127.0.0.1:50038/appservice/common/js/service.js:3:17
    at require (http://127.0.0.1:50038/appservice/__dev__/WAService.js:18:27248)
    at http://127.0.0.1:50038/appservice/__dev__/WAService.js:18:26997

Errors 2: VM1451:1 pages/index/index.js 出现脚本错误或者未正确调用 Page()

Errors 3: VM1451:1 pages/create/create.js 出现脚本错误或者未正确调用 Page()

Warning 1: VM1451:1 Page[pages/index/index] not found. May be caused by: 1. Forgot to add page route in app.json. 2. Invoking Page() in async task.

Warning 2:  WXML Runtime warning
VM1520:2 ./pages/index/index.wxml
(anonymous) @ VM1520:2
VM1520:3  Now you can provide attr "wx:key" for a "wx:for" to improve performance.
  21 |     \<view class="calendar">
  22 |       \<view class="week">
\> 23 | \<block wx:for="{{days}}" wx:for-index="dayIdx" wx:for-item="dayItem">
           \|====                 \^
  24 |           \<view class="days {{dayIdx==0||dayIdx==6?'weekend':''}}">
  25 |             \{{dayItem}}
  26 |           \</view>
(anonymous) @ VM1520:3

**Comment by GeduoWang** [comment]
已经解决了，按照1楼和3楼的解法ok
